DOTFILES="$(cd "$(dirname "$0")" && pwd)"

ln -s "$DOTFILES/bash/bash_aliases"      "$HOME/.bash_aliases"
ln -s "$DOTFILES/bash/bash_functions"    "$HOME/.bash_functions"
ln -s "$DOTFILES/bash/profile"           "$HOME/.bash_profile"
ln -s "$DOTFILES/bash/bashrc"            "$HOME/.bashrc"
ln -s "$DOTFILES/bash/bash_functions"    "$HOME/.functions"
ln -s "$DOTFILES/bash/profile"           "$HOME/.profile"
ln -s "$DOTFILES/tmux"                   "$HOME/.tmux"
ln -s "$DOTFILES/tmux/tmux.conf"         "$HOME/.tmux.conf"
ln -s "$DOTFILES/vim"                    "$HOME/.vim"
ln -s "$DOTFILES/zsh/zshrc"             "$HOME/.zshrc"
ln -s "$DOTFILES/tmux"                   "$HOME/.config/tmux"
ln -s "$DOTFILES/nvim"                   "$HOME/.config/nvim"
ln -s "$DOTFILES/ranger"                 "$HOME/.config/ranger"
ln -s "$DOTFILES/powerlevel10k/p10k.zsh" "$HOME/.p10k.zsh"

